# Generated by Django 3.1 on 2020-09-15 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200915_1825'),
        ('productos', '0002_auto_20200902_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del material')),
                ('descripcion', models.CharField(max_length=250, verbose_name='Breve descripcion del material')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='entity',
        ),
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.entity')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='productos.product')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.entity')),
                ('material', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='productos.material')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='productos.material'),
        ),
    ]
