# Generated by Django 3.1 on 2020-09-17 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200915_1843'),
        ('productos', '0003_auto_20200915_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant', models.IntegerField()),
                ('date_env', models.DateTimeField(auto_now_add=True)),
                ('date_recp', models.DateField(auto_now=True)),
                ('recp', models.BooleanField(default=False)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.entity')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='productos.product')),
            ],
        ),
        migrations.CreateModel(
            name='SendProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant', models.IntegerField()),
                ('date_env', models.DateTimeField(auto_now_add=True)),
                ('date_recp', models.DateField(auto_now=True)),
                ('recp', models.BooleanField(default=False)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.entity')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='productos.product')),
            ],
        ),
        migrations.DeleteModel(
            name='Movimient',
        ),
    ]
