# Generated by Django 3.1 on 2020-09-18 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_auto_20200917_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialstock',
            name='cantidad',
        ),
        migrations.AddField(
            model_name='materialstock',
            name='peso',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
