# Generated by Django 3.1 on 2020-09-22 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20200918_2045'),
        ('productos', '0008_auto_20200922_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstock',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.entity'),
        ),
    ]
