# Generated by Django 3.1 on 2020-09-23 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20200923_1301'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productos', '0010_auto_20200922_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovPStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('EP', 'Entrada de Producto'), ('SP', 'Salida de Producto')], max_length=2)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.entity')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.product')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MovMStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('EM', 'Entrada de Material'), ('SM', 'Salida de Material')], max_length=2)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.entity')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.material')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
