# Generated by Django 3.1 on 2020-09-24 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0011_movmstock_movpstock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialstock',
            name='descripcion',
        ),
        migrations.AlterField(
            model_name='materialstock',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.material'),
        ),
    ]
