# Generated by Django 3.1.2 on 2020-10-13 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0012_auto_20200924_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='movpstock',
            name='peso',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
