# Generated by Django 3.1 on 2020-09-04 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200904_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entity',
            old_name='país',
            new_name='pais',
        ),
    ]
