# Generated by Django 3.1 on 2020-09-18 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200915_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepunt',
            name='visitas',
            field=models.PositiveIntegerField(verbose_name='Cantidad de visitas por año'),
        ),
    ]
