# Generated by Django 3.1.2 on 2020-10-15 00:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20200923_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepunt',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profilepunt',
            name='punt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.entity'),
        ),
    ]
